#!/usr/bin/env bash

## debug settings

nodebug() {
  set +v +x +u
}

setdebug() {
  set -v -x -u
}

nodebug

## searching
## ??

## shell and file ops
function d() {
  ls -h --color -laF ${*} 2>&1 | bat
}

alias apt-get='apt-get -y'
alias l=ls
alias ls='ls --color'
alias lsort='ls -Sharl'
alias df='df -h'

alias diffy='diff --color=always -y --suppress-common-lines'
alias j='jobs -l'
alias -- -='cd -'

alias ...='cd ../..'
alias ....='cd ../../..'
alias h='history 75'
alias m='$PAGER'

alias rm='rm -vi'
alias cp='cp -vi'
alias mv='mv -vi'

alias rmf='/bin/rm -fv'
alias cpf='/bin/cp -fv'
alias mvf='/bin/mv -fv'

alias -- +x='chmod +x'
alias -- -x='chmod -x'

## common

alias rehash='source ~/.bashrc'
alias re=rehash
alias ircname=echo
alias sed='sed -r'
alias lane='perl -lane'

alias wget='wget --no-check-certificate'
alias vol='mpc volume'

export CGREP_COLOR='-aHn --color=always'
alias cgrep="egrep ${CGREP_COLOR}"
alias grep='egrep'

function hgrep() {
  cgrep -ar "${1}" ~/.history | sed 's#^.*/.history/bash.##g' | sort -t ':' -k3 | ccze -A
}

alias discus='discus|grep -v "0 KB"'

alias acpi='acpi -V'

alias opkg='opkg -t /data/opkg --cache /data/opkg-cache'

test -d ~/.history || mkdir ~/.history
test -d ~/.vim/undodir || mkdir -p ~/.vim/undodir

TTY=$(echo $(tty) | sed -e s@/dev/@@ -e s@pts/@@ )
[[ -n "$TTY" ]] && export HISTFILE="${HOME}/.history/bash.history.${TTY}"

if [ -t 1 ]; then
  bind "set completion-ignore-case on"
  bind "set completion-map-case on"
  bind "set show-all-if-ambiguous on"
  bind -r "\C-w" # finally ...
  bind "\C-w":backward-kill-word
fi

alias sensors='pssh -Ph ~/.pssh-sensors'
alias sensorstats="sensors 'uname -a; top -bn1|head -4;df -h .|tail -1; '"
alias senscreen='screen -S sensors -c /root/.screen/sensors.screenrc'
#echo "$HOSTNAME:${PPWD##*/}/${PWD##*/}" ? excuse me?
alias services='service --status-all | egrep \\+'
alias iwinfo='iw phy phy0 info'

alias scrx='screen -rx'
alias scrls='screen -ls'
alias system-overview='(scrls |& grep sysmon) || screen -S sysmon -T screen -c /root/.screen/system-overview.screenrc'

alias beepwar='while true; do echo  > /dev/tty1; sleep 1; echo  > /dev/tty1; sleep 1; ssh timer "echo  > /dev/tty1"; sleep 1; ssh timer "echo  > /dev/tty1"; sleep 2; done'

#alias scrsw='while true; do scrsel 0; sleep 7; scrsel 1; sleep 9; scrsel 2; sleep 8; scrsel 3; sleep 7; scrsel 4; sleep 5; done'

function scrsw() {
  NUM=$1
  WAIT=$2

  test -z "$WAIT" && echo "$0 MAXSCREENS WAIT" && return
  
  while true; do
    for i in `seq 0 ${NUM}`; do
      scrsel $i
      sleep $(( $WAIT + $(($RANDOM % 4))))
    done
  done
}

function pub() {
  TOPIC=$1; shift
  mosquitto_pub -t "${TOPIC}" -m "$*"
}
