#!/bin/bash
# shell sync v.000000

SS_RC="${BASH_SOURCE}"
SS_VERSION='v.002000 A'
SS_ABOUT='github/terbo/shellsync'


SS_CFG_USESTATIC="$HOME/.ss"

## 
##__Network

# fill out only one other is auto
declare -a SS_CPUS_HOSTS=(tk timer kali rpi hp nex sfive iplanet wrt1 wrt2 ) 
               #epic4g unico cracked zte - offline
SS_CPUS_IPS=[]


##
##__User config files

declare -a SS_CFG_FILES_TCSHRC=(/etc/csh.cshrc /etc/csh/login.d/csh.cshrc /root/.tcshrc /etc/csh/csh.login/tcshrc-kali /root/.cshrc /home/cb/.cshrc /home/cb/.tcshrc)

declare -a SS_CFG_FILES_BASHRC=(/etc/bashrc /root/.bashrc /root/.bash_aliases /home/cb/.bashrc)

declare -a SS_CFG_FILES_VIMRC=(/etc/vim/vim.local /root/.vimrc)


declare -a SS_CFG_FILES_HISTORY=(/root/.history/ /root/.bash_history /root/.dbshell /root/.ptpython/history /root/.mysql_history)

declare -a SS_CFG_FILES=(/root/.ssh/ /root/.BitchX/ /root/.vim/ /root/.mplayer/ /root/.w3m/ /root/.config/htop/ /root/.inputrc /root/bin)

##
##__defaults


SS_CFG_VERBOSE=1
SS_CFG_DEBUG=0
SS_CFG_TRACE=1

SS_CFG_USEREST=0
SS_CFG_USERESTY=0

SS_CFG_USEWEB=0
SS_CFG_USEHTTPD=0

SS_CFG_USEWGET=0
SS_CFG_USECURL=0


SS_CFG_USETMP=1
SS_CFG_USECRON=0
SS_CFG_USEDIFF=0

SS_CFG_USEBACKUP='dv8:k:nex:sfive:epic4g'


declare -a SS_LOG_PRIOS=(INFO DEBUG ERROR)
SS_LOG_FILE=1
SS_LOG_STDOUT=1
SS_LOG_COLOR=1
SS_LOG_CURSES=1


SS_CFG_MOTDDYNAMIC=1
SS_CFG_MOTDTABLE=1
SS_CFG_MOTDSUMMARIZE=1
SS_CFG_MOTDFIGLET=1
SS_CFG_MOTDTOILET=1


##__Chat and info retrieval
SS_CFG_MARKOV=1
SS_CFG_CHATTYCATTY=1
SS_CFG_CHATTYCATTY_SEARCHLIMIT=30
SS_CFG_CHATTYCATTY_TALKLIMIT=3.5

SS_CFG_BASHBOT=1
SS_CFG_BASHBOTNET=1


##__Shells

SS_CFG_USETCSH=1
SS_CFG_USEBASH=1

## Pager
SS_CFG_USELESS=1

## Editor
SS_CFG_USEVIM=1
SS_CFG_USEEMACS=0

## Web Browser
SS_CFG_USELYNX=0
SS_CFG_USEW3M=1
SS_CFG_USELINKS=0

SS_CFG_FILES_BASHRC=[]
SS_CFG_FILES_VIMRC=[]
SS_CFG_FILES_HISTORY=[]
SS_CFG_FILES_TCSHRC=[]

##__Program versions

SS_VER_SED=''
SS_VER_GREP=''
SS_VER_BUSYBOX=''
SS_VER_GNU_BINUTILS=1
SS_VER_GNU_COREUTILS=1

SS_VER_VIM=''
SS_VER_LESS=''
SS_VER_SCREEN=''
SS_VER_NMAP=''
SS_VER_SSH=''

SS_VER_PERL=''
SS_VER_AWK=''
SS_VER_PYTHON=''

SS_VER_CPAN=''
SS_VER_PIP=''

SS_VER_APT=''

SS_SYS_OS=''
SS_SYS_OSVERSION=''

SS_SYS_MEMINFO=''
SS_SYS_DISKS=''
SS_SYS_NET=''

SS_OS_JAVA=''
SS_OS_UNIX=''
SS_OS_IOS=''
SS_OS_WIN=''
SS_OS_JS=''

export ${!SS_*} ${!SHELLSYNC*}
