#!/usr/bin/python

import os
import manuf
import socket
from datetime import datetime as dt
from sys import argv

LEASEFILE='/var/lib/misc/dnsmasq.leases'

leases = open(LEASEFILE,'r').read().split('\n')
out = {}
ips = list()
m = manuf.MacParser()
show = set()
opts = set()
stats = {'leases': 0} #, 'firstlease': dt.now(), 'lastlease': False, 'prevlease': False }


if len(argv):
    for arg in argv:
        if arg == '-h': show.add('host')
        if arg == '-m': show.add('mac')
        if arg == '-i': show.add('ip')
        if arg == '-n': show.add('name')
        if arg == '-o': show.add('oui')
        if arg == '-N': opts.add('NL')
        if arg == '-S': opts.add('stat')

for lease in leases:
  l = lease.split()
  
  if l:
    (time,mac,ip,name) = l[0:4] 
    oui = m.get_manuf(mac)
    
    try:
        host = socket.gethostbyaddr(ip)[0][0:12] + '.local'
    except:
        host = ''

    date = dt.strftime(dt.fromtimestamp(float(time)),'%D %R')
     
    out[mac] = {'time': time, 'date': date,
                'name': name, 'ip': ip,
                'host': host, 'oui': oui,
                'mac': mac}
    
    if 'stat' in opts:
        stats['leases'] = stats['leases'] + 1
        '''print(out[mac]) 
        if out[mac]['time'] < stats['firstlease']:
            stats['firslease'] = out[mac]['time']
        
        if out[mac]['time'] > stats['prevlease']:
            stats['lastlease'] = out[mac]['time']
        
        stats['prevlease'] = out[mac]['time']'''


for mac in sorted(out,
    cmp=lambda a,b: cmp(out[b]['time'], out[a]['time'])):
  info = out[mac] 
  
  if(len(show)):
    print ', '.join([ info[x] for x in show ]),
    if 'NL' in opts: print ''

  else:
      print("%-15s\tleased @ %s\n    %s %s\t%s\n    %s" % \
        (info['name'], info['date'], info['host'], info['ip'],
        mac,info['oui']))
      if 'NL' in opts: print ''

if 'stat' in opts:
    print stats
