#!/bin/bash

#declare -A screen_select=(0=4, 1=5, 2=4, 6=5, 8=10)
# for s

${1} &

screen -X select 0
while true; do
  screen -X next
  sleep $(( ($RANDOM % 10) + 5 ))
done

#select 0
#  sleep 4
#  screen -X select 1
#  sleep 5
#  screen -X select 2
#  sleep 4
#  screen -X select 6
#  sleep 5
#  screen -X select 8
#  sleep 10
#done
